PI2 = Math.PI/2

FIELD_WIDTH = 120
FIELD_WIDTH2 = FIELD_WIDTH/2
FIELD_HEIGHT = 77
FIELD_HEIGHT2 = FIELD_HEIGHT/2

BALL_SIZE = 2
PLAYER_SIZE = 4
PLAYER_SIZE2 = PLAYER_SIZE/2
SELECT_SIZE = 5

ANIM_FACTOR = 300
CAM_ANIM_FACTOR = 3000

BARS_MAX_HEIGHT = 15
BARS_MIN_HEIGHT = 1
